fastlane_version "1.80.0"

default_platform :ios

platform :ios do

	lane :testing do
		scan(
			project: "EpochConverter.xcodeproj",
			scheme: "EpochConverter"
		)

		slather(
			proj: "EpochConverter.xcodeproj",
			travis: true,
			coveralls: true
		)
	end

end
